### ISSUE TITLE
Cookies not setting in Chrome

### ISSUE THREAD

**Issue by RussellJonesPersonal** [camsjams/jquery-style-switcher#1]
Excellent script, but cookies don't appear to be setting in Chrome. I'm afraid for user security reasons I can't post my code, but I've used your script without alteration on a site containing 5 pages, and in every browser it remembers color settings - but not in Chrome.

**Comment by camsjams** [comment]
This has been tested in all browsers. I've just tried our demo page here at:
http://etalx.com/jquery-style-switcher/tests/

And it works in latest Chrome (Version 40.0.2214.115 m) and Chrome Canary (Version 43.0.2313.0 canary (64-bit)).

Could you try to see if the bug occurs on the demo page and also provide a version number?
