### ISSUE TITLE
Cookie is saved under the current path

### ISSUE THREAD

**Issue by SteveVaneeckhout** [camsjams/jquery-style-switcher#2]
The code doesn't set a path of the cookie. So if I switch the style of the page under http://example.org/products/xyz the style won't be switched under http://example.org/support/some-article
Is it possible to at least provide an option to set a custom path or set the default to '/'?

**Comment by camsjams** [comment]
Thanks @raf-vs 

@SteveVaneeckhout we can see about adding that as an option too
